// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id mrptukahxloqpdqiaxkb > lib/database.types.ts
// Or use the Supabase dashboard to generate types:
// https://supabase.com/dashboard/project/mrptukahxloqpdqiaxkb/settings/api
// Click "Generate TypeScript types" and copy the output here

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      settings: {
        Row: {
          id: string
          site_name: string
          contact_email: string
          contact_phone: string
          address: string
          google_analytics_id: string | null
          announcement_bar: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          site_name: string
          contact_email: string
          contact_phone: string
          address: string
          google_analytics_id?: string | null
          announcement_bar?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          site_name?: string
          contact_email?: string
          contact_phone?: string
          address?: string
          google_analytics_id?: string | null
          announcement_bar?: Json
          created_at?: string
          updated_at?: string
        }
      }
      home_content: {
        Row: {
          id: string
          hero: Json
          values: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          hero: Json
          values: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          hero?: Json
          values?: Json
          created_at?: string
          updated_at?: string
        }
      }
      products: {
        Row: {
          id: string
          title: string
          price: number
          category: string
          image: string
          description: string | null
          inventory: Json | null
          variants: Json | null
          featured: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          price: number
          category: string
          image: string
          description?: string | null
          inventory?: Json | null
          variants?: Json | null
          featured?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          price?: number
          category?: string
          image?: string
          description?: string | null
          inventory?: Json | null
          variants?: Json | null
          featured?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      testimonials: {
        Row: {
          id: number
          name: string
          role: string
          quote: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: number
          name: string
          role: string
          quote: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          name?: string
          role?: string
          quote?: string
          created_at?: string
          updated_at?: string
        }
      }
      pages: {
        Row: {
          id: string
          slug: string
          title: string
          content: Json
          meta_title: string | null
          meta_description: string | null
          meta_image: string | null
          published: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          title: string
          content: Json
          meta_title?: string | null
          meta_description?: string | null
          meta_image?: string | null
          published?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          title?: string
          content?: Json
          meta_title?: string | null
          meta_description?: string | null
          meta_image?: string | null
          published?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      media: {
        Row: {
          id: string
          filename: string
          url: string
          file_type: string
          file_size: number
          folder: string | null
          tags: string[] | null
          alt_text: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          filename: string
          url: string
          file_type: string
          file_size: number
          folder?: string | null
          tags?: string[] | null
          alt_text?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          filename?: string
          url?: string
          file_type?: string
          file_size?: number
          folder?: string | null
          tags?: string[] | null
          alt_text?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      calendar_events: {
        Row: {
          id: string
          title: string
          description: string | null
          start_time: string
          end_time: string
          instructor_id: string | null
          class_type: string
          capacity: number | null
          recurring_pattern_id: string | null
          occurrence_date: string | null
          is_recurring_generated: boolean
          is_recurring_preserved: boolean
          recurring_series_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          description?: string | null
          start_time: string
          end_time: string
          instructor_id?: string | null
          class_type: string
          capacity?: number | null
          recurring_pattern_id?: string | null
          occurrence_date?: string | null
          is_recurring_generated?: boolean
          is_recurring_preserved?: boolean
          recurring_series_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          description?: string | null
          start_time?: string
          end_time?: string
          instructor_id?: string | null
          class_type?: string
          capacity?: number | null
          recurring_pattern_id?: string | null
          occurrence_date?: string | null
          is_recurring_generated?: boolean
          is_recurring_preserved?: boolean
          recurring_series_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      calendar_recurring_patterns: {
        Row: {
          id: string
          pattern_type: string
          interval: number
          days_of_week: number[] | null
          end_date: string | null
          title: string
          description: string | null
          class_type: string
          instructor_id: string | null
          capacity: number | null
          starts_on: string
          start_time_local: string
          end_time_local: string
          timezone: string
          is_active: boolean
          generation_horizon_days: number
          last_materialized_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          pattern_type: string
          interval?: number
          days_of_week?: number[] | null
          end_date?: string | null
          title?: string
          description?: string | null
          class_type?: string
          instructor_id?: string | null
          capacity?: number | null
          starts_on?: string
          start_time_local?: string
          end_time_local?: string
          timezone?: string
          is_active?: boolean
          generation_horizon_days?: number
          last_materialized_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          pattern_type?: string
          interval?: number
          days_of_week?: number[] | null
          end_date?: string | null
          title?: string
          description?: string | null
          class_type?: string
          instructor_id?: string | null
          capacity?: number | null
          starts_on?: string
          start_time_local?: string
          end_time_local?: string
          timezone?: string
          is_active?: boolean
          generation_horizon_days?: number
          last_materialized_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      calendar_recurring_exceptions: {
        Row: {
          id: string
          recurring_pattern_id: string
          exception_date: string
          reason: string | null
          created_at: string
        }
        Insert: {
          id?: string
          recurring_pattern_id: string
          exception_date: string
          reason?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          recurring_pattern_id?: string
          exception_date?: string
          reason?: string | null
          created_at?: string
        }
      }
      calendar_bookings: {
        Row: {
          id: string
          event_id: string
          user_id: string
          status: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          event_id: string
          user_id: string
          status?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          user_id?: string
          status?: string
          created_at?: string
          updated_at?: string
        }
      }
      instructors: {
        Row: {
          id: string
          name: string
          email: string | null
          bio: string | null
          image_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          email?: string | null
          bio?: string | null
          image_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          email?: string | null
          bio?: string | null
          image_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
